### ISSUE TITLE
[BUG] Link for "Andrea Grandi" feed is wrong

### ISSUE THREAD

**Issue by andreagrandi** [python/planet#120]
Hi, I want to notify you of a bug/problem that is happening on the Planet.

I am using:  
**O.S**: any 
**Browser**: any 
**Platform**: (mobile, tablet, desktop)  
## Problem

If you go on http://planetpython.org the **Andrea Grandi** link points to http://planetpython.org/ instead of pointing to the correct feed that is https://www.andreagrandi.it/category/python/feed/
## Details

The configuration seems to be fine: https://github.com/python/planet/blob/master/config/config.ini#L1784
The only thing I would amend is that I'm serving it through **https** not http.

I can make a PR to change the url to be https but I don't think this is breaking anything because server side I've a redirect rule, so even the http "should" be valid.

Could you please have a look and check what else could be wrong?

Thanks.

**Comment by rochacbruno** [comment]
Looking in to RSS validator the only problems reported is ``script`` and ``iframe`` in syndicated content.

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.andreagrandi.it%2Fcategory%2Fpython%2Ffeed

But I am not sure if this is the cause of your feed not being fetched.

Maybe @tjguk have some clue about it.

**Comment by andreagrandi** [comment]
@rochacbruno Hi Bruno, thanks for your very quick reply. I hope the feed can work regardless of the content of the posts :) I can make sure my Wordpress isn't broken in general, but it would be quite difficult to check every post I do :/
Is there any test I can do or any other information I can provide to help you find the problem?

Thanks

**Comment by tjguk** [comment]
We've always been bit wobbly on https feeds. One fix was applied back in
2014:

  https://github.com/python/planet/commits/master/code/planet.py

but presumably that hasn't fixed everything.

@andreagrandi you're very welcome to track down the issue; otherwise I
or one of the other maintainers can have a look, but I don't have time
just at the moment.

**Comment by andreagrandi** [comment]
@tjguk I can't believe I'm the only one using https on my blog :P
As far as I remember, since I asked to be part of the Planet, this has never worked. Just to exclude the fact that I switched from StartSSL to LetsEncrypt or the fact that I have CloudFlare in front of it.
I've no idea where to start from to track down the problem as I would need to run the whole platform locally and debug it to understand what's going on, but I remain available if you need me to change anything on my side just to understand what's wrong.

Cheers

**Comment by tjguk** [comment]
@andreagrandi thanks; I understand. TBH I thought we'd fixed it two
years ago so it rather went off my radar.

Thanks for your offer of cooperation; I will try to run up a test rig
and reproduce.

**Comment by tjguk** [comment]
Just to confuse things: I've run up a test version and your blog links
correctly to https://www.andreagrandi.it. So it looks as though we may
have some kind of cacheing issue with the data. I don't have access to
the actual server to investigate this, so I'll try to ping the
infrastructure team to see if someone can look at it.

(Unless one of the other planet maintainers can look into it...?)

**Comment by tjguk** [comment]
On 09/03/2016 11:05, Tim Golden wrote:
> Just to confuse things: I've run up a test version and your blog links
> correctly to https://www.andreagrandi.it. So it looks as though we may
> have some kind of cacheing issue with the data. I don't have access to
> the actual server to investigate this, so I'll try to ping the
> infrastructure team to see if someone can look at it.
> 
> (Unless one of the other planet maintainers can look into it...?)
> 

Ok; I've managed a little more debugging. I still think that *this*
issue is down to overzealous cacheing of a previous situation. But We
have a slightly wider situation.

The Planet template expects the Channel object to have a "link". This
"link" is *not* the URL supplied via the config file; nor is it a
redirected version. It's actually the <link> element from the RSS2/Atom
feed. If a Channel doesn't have one, the Channel is listed regardless,
only with an empty href="", resulting in a link to the page we're on.

For the dozen or so spot-checks I tried, the most common situation is a
dead feed URL. Which highlights the number of dead links we have. Some
are surely dead and gone. But others are almost certainly
reconfigurations (new blog engine, new domain, whatever) which we can
recover from. So I'll put out a call to the Python community, urging
people to check their links and/or submit new requests / PRs.

I suppose that, at some point, Andrea's feed gave this result, possibly
because of some https-validation issue (or whatever). As per my previous
update I'll give it a few hours and, if no-one responds here, then I'll
get in touch with the infrastructure team.

**Comment by andreagrandi** [comment]
Hi @tjguk and thank you so much for your debugging! Is there anything else from my side that could be done to help you?

Cheers

**Comment by andreagrandi** [comment]
@tjguk hi Tim, I've just checked again (I understand the feed needed some time to update itself?), but it's still pointing to the wrong link

**Comment by tjguk** [comment]
I'm conscious that this is still an issue despite clearing the cache.
And yet, if I build locally, the link is correct. Can anyone else
reproduce from a test build?

**Comment by andreagrandi** [comment]
@tjguk could it be because the deployed version that is running on planet is different/older compared to latest version you try to run locally?

**Comment by tjguk** [comment]
In theory, yes. But my understanding is that the scheduled update (every
3 hours or so) is effectively a "git pull" from the entire repo, not
just the config. Certainly I and others have made more or less small
code changes in the past which have shown up on the live site.

I might force a hidden change, just to make sure we're running the
version I think we're running.

**Comment by allanderek** [comment]
Just in case it hasn't been noticed here, but Andrea's blog is not the only Subscription link that is pointing to 'planetpython.org', eg. 2General, A little bit of Python, and the first link points to planetpython.org/opml.xml and I sort of think is not meant to be there at all (but I don't know).

**Comment by tjguk** [comment]
Thanks, Allan. Yes: we know (at least: I know) that there are several.
Many of them are the ones which have missing or invalid feeds & which we
haven't weeded out. Andrea's is one -- maybe not the only one -- whose
feed appears to be valid but which is still missing its link.

**Comment by andreagrandi** [comment]
Hi, sorry to bother you again, but... are there any updates on this issue? Cheers

**Comment by andreagrandi** [comment]
Ping @tjguk are there any updates on this bug? Thank you so much. Cheers

**Comment by tseaver** [comment]
@allanderek the OPML link is meant to be there.  Interestingly, it has @andreagrandi's feed in it correctly.

@tjguk I can confirm that building the feed locally with a stripped-down configuration generates files with correct feed URL and items for @andreagrandi's feed.  How were you able to clear the cache?  AFAICT, the [`planet-cache.py` script](https://github.com/python/planet/blob/master/code/planet-cache.py) would only work if run on the actual server.  If you can get there, then @andreagrandi's feed would be cached in `/srv/cache/www.andreagrandi.it,category,python,feed`.

**Comment by andreagrandi** [comment]
Hi @tjguk I hope I'm not disturbing you, but... do you have any update on this :) ? Thank you so much.

**Comment by ewdurbin** [comment]
Seems this has been resolved, and was caused by TLS feed fetching issue. The link mentioned is now rendered correctly.
