### ISSUE TITLE
Add Feed: www.dspillustrations.com

### ISSUE THREAD

**Issue by mmatthe** [python/planet#200]
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

**My Name/Blog Name**: DSPIllustrations.com  

**My Blog RSS or ATOM Python specific feed url**: http://dspillustrations.com/static/dspillustrations.rss.xml
 
## I checked the following required validations: (mark all 4 with [x])

1. [X] My feed is valid, I checked using http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fdspillustrations.com%2Fstatic%2Fdspillustrations.rss.xml and it is valid!
2. [X] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [X] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [X] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

**Comment by mmatthe** [comment]
May I ask if somebody can have a look at my proposal?

**Comment by tjguk** [comment]
I've asked for an opinion from the other Planet maintainers because, while the content *uses* Python to illustrate DSP, it's not essentially *about* Python. However, we do already have other feeds which are a little tangential so it may not be a problem. We'll have a discussion among ourselves and get back to you. (And apologies again for the delay in picking this up in the first place).

**Comment by tjguk** [comment]
Thanks; that should appear in the next refresh (usually a few hours)
