### ISSUE TITLE
Planet Python not showing posts

### ISSUE THREAD

**Issue by techiediaries** [python/planet#262]
# REPORT A BUG/PROBLEM
-------------------------------------------------------------------------------

Hi, I want to notify you of a bug/problem that is happening on the Planet.

## Problem

Planet Python showed one post then stopped showing my posts 

This is my feed [https://www.techiediaries.com/tag/django/index.xml](https://www.techiediaries.com/tag/django/index.xml)

Please tell me If I need to change anything in the feed

Thanks.

---------------------------------------------------------------------------------

**Comment by tseaver** [comment]
Your feed loads fine when I run locally, but only the latest article (the others are hidden due to the planet's "new feed" filter).  The latest entry is older than the current cut-off, so I can't look to see if it would display on the live planet.

Please ping me here when you have published a new article to the feed.
