### ISSUE TITLE
Pete Hunt

### ISSUE THREAD

**Issue by Tjorriemorrie** [python/planet#284]
# REMOVE FEED
------------------------------------------------------------------------------

The feed of Peter Hunt is not about python.
http://www.petehunt.net

**Comment by The-Judge** [comment]
Looks like intentionally abuse to me.

**Comment by smontanaro** [comment]
Thinking a bit more strategically, what happened to let this in?

* Did the culprit go to the necessary lengths to make it appear to be a
Python-related blog, then pulled a switcheroo after the feed was active?

* Did nobody check it out before approval?

I suppose we could implement some checker to monitor the former case. The
latter could be handled by requiring an affirmative LGTM from a human
before adding the feed.

There are a number of checkers running for bugs.python.org which do all
sorts of routine drudgery (check for assignment or backport possibility,
etc). I imagine any one of them could serve as a skeleton for either one of
these checks. I've done nothing with Github's APIs before (I presume that's
how the magic happens), but would be happy to at least take a look.

Skip

**Comment by tseaver** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 05/07/2018 09:59 AM, Skip Montanaro wrote:
> Thinking a bit more strategically, what happened to let this in?
> 
> * Did the culprit go to the necessary lengths to make it appear to be
> a Python-related blog, then pulled a switcheroo after the feed was
> active?

The feed was added in the original git commit for the repository[1], and
its URL was last updated eight years ago[2].  Does it seem a likely
hypothesis is that the legitimate Python user gave up the domain, or sold
it?  But odd that the path part of the URL would remain valid.

> * Did nobody check it out before approval?
> 
> I suppose we could implement some checker to monitor the former case.
> The latter could be handled by requiring an affirmative LGTM from a
> human before adding the feed.
> 
> There are a number of checkers running for bugs.python.org which do
> all sorts of routine drudgery (check for assignment or backport
> possibility, etc). I imagine any one of them could serve as a skeleton
> for either one of these checks. I've done nothing with Github's APIs
> before (I presume that's how the magic happens), but would be happy to
> at least take a look.


[1]
https://github.com/python/planet/commit/1f11b914edd602df1fe2652e83697a12284
d8b2d

[2]
https://github.com/python/planet/commit/52ccad402eb749137f9e0a7f11d5eec0d3c
b6ea3

Tres.
- -- 
===================================================================
Tres Seaver          +1 540-429-0999          tseaver@palladion.com
Palladion Software   "Excellence by Design"    http://palladion.com
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlrwZxkACgkQFXKVXuSL+CN4ggCfX19UP+tFecIb0o7cLLARBEIu
GvkAnA+mcY40GIz0ZCum2Yzu+vT6CmcR
=zCS8
-----END PGP SIGNATURE-----
