### ISSUE TITLE
please remove and ban user posting nudity

### ISSUE THREAD

**Issue by rgommers** [python/planet#344]
https://python-catalin.blogspot.com/2019/01/detect-nudity-with-nudepy-python-module.html posted a post containing imagery that likely violates the PSF code of conduct, for the second time. The first time I commented on that post notifying that person of the CoC violation, and the post disappeared from Planet Python shortly after. Now it's a repost of the exact same thing. Please ban this user permanently.

**Comment by matrixise** [comment]
@rgommers We can't ban a user because the planet is not a group. Now, we can stop to merge a PR from this person. But to be sure, I prefer to ask to the PSF Board and the CoC work group.

**Comment by rgommers** [comment]
> We can't ban a user because the planet is not a group.

I don't get that, you're running a feed aggregator so you can add or remove any feed. Please just remove this feed.

**Comment by matrixise** [comment]
@rgommers I will wait for the answer from the PSF about this eventual CoC because I am not an expert in English and with the Code of Conduct. Thank you for your patience.

**Comment by rochacbruno** [comment]
This issue has been discussed on python planet mailing list.

The author has changed his post, removed the image and that is why feed added back.

I checked the post and the image is not there anymore.

see: https://github.com/python/planet/pull/343

**Comment by rochacbruno** [comment]
And just for the record, I want to add that the author has not posted pornography. 

It is an article about a Python library used to detect nudity, the kind of library which is useful exactly for the purpose of checking violation of CoCs.

The image there was an Human Anatomy Model, the same thing we see in school books, that was not even human image but a 3D model.

There is a very thin line here which separates CoC violation from technology to detect this.

Anyway, now the author has removed the image this issue is resolved.

**Comment by rgommers** [comment]
thanks @rochacbruno 

> There is a very thin line here which separates CoC violation from technology to detect this.

Fully agreed. This is borderline. I only opened this issue because the image reappeared a month after I first pointed out to the author that it was potentially problematic. He also removed my comment on his blog, so the whole thing didn't look like it was done in good faith. I can't be sure though, so let's leave it at this. Closing this issue.
